// Code generated by protoc-gen-go. DO NOT EDIT.
// source: star-wars-service.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlanetCollection struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Climate              string   `protobuf:"bytes,2,opt,name=climate,proto3" json:"climate,omitempty"`
	Terrain              []string `protobuf:"bytes,3,rep,name=terrain,proto3" json:"terrain,omitempty"`
	TimesOnMovies        int32    `protobuf:"varint,4,opt,name=timesOnMovies,proto3" json:"timesOnMovies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlanetCollection) Reset()         { *m = PlanetCollection{} }
func (m *PlanetCollection) String() string { return proto.CompactTextString(m) }
func (*PlanetCollection) ProtoMessage()    {}
func (*PlanetCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_67d7a717a5d4f718, []int{0}
}

func (m *PlanetCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlanetCollection.Unmarshal(m, b)
}
func (m *PlanetCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlanetCollection.Marshal(b, m, deterministic)
}
func (m *PlanetCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanetCollection.Merge(m, src)
}
func (m *PlanetCollection) XXX_Size() int {
	return xxx_messageInfo_PlanetCollection.Size(m)
}
func (m *PlanetCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanetCollection.DiscardUnknown(m)
}

var xxx_messageInfo_PlanetCollection proto.InternalMessageInfo

func (m *PlanetCollection) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlanetCollection) GetClimate() string {
	if m != nil {
		return m.Climate
	}
	return ""
}

func (m *PlanetCollection) GetTerrain() []string {
	if m != nil {
		return m.Terrain
	}
	return nil
}

func (m *PlanetCollection) GetTimesOnMovies() int32 {
	if m != nil {
		return m.TimesOnMovies
	}
	return 0
}

func init() {
	proto.RegisterType((*PlanetCollection)(nil), "v1.PlanetCollection")
}

func init() { proto.RegisterFile("star-wars-service.proto", fileDescriptor_67d7a717a5d4f718) }

var fileDescriptor_67d7a717a5d4f718 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x2e, 0x49, 0x2c,
	0xd2, 0x2d, 0x4f, 0x2c, 0x2a, 0xd6, 0x2d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x54, 0x6a, 0x60, 0xe4, 0x12, 0x08, 0xc8, 0x49, 0xcc,
	0x4b, 0x2d, 0x71, 0xce, 0xcf, 0xc9, 0x49, 0x4d, 0x2e, 0xc9, 0xcc, 0xcf, 0x13, 0x12, 0xe2, 0x62,
	0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x24, 0xb8,
	0xd8, 0x93, 0x73, 0x32, 0x73, 0x13, 0x4b, 0x52, 0x25, 0x98, 0xc0, 0xc2, 0x30, 0x2e, 0x48, 0xa6,
	0x24, 0xb5, 0xa8, 0x28, 0x31, 0x33, 0x4f, 0x82, 0x59, 0x81, 0x19, 0x24, 0x03, 0xe5, 0x0a, 0xa9,
	0x70, 0xf1, 0x96, 0x64, 0xe6, 0xa6, 0x16, 0xfb, 0xe7, 0xf9, 0xe6, 0x97, 0x65, 0xa6, 0x16, 0x4b,
	0xb0, 0x28, 0x30, 0x6a, 0xb0, 0x06, 0xa1, 0x0a, 0x26, 0xb1, 0x81, 0x5d, 0x63, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xe0, 0x1b, 0x12, 0x25, 0xa8, 0x00, 0x00, 0x00,
}
