// Code generated by protoc-gen-go. DO NOT EDIT.
// source: swapi-response.proto

package swapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SwapiResponse struct {
	Count                int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Next                 string                 `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	Previous             string                 `protobuf:"bytes,3,opt,name=previous,proto3" json:"previous,omitempty"`
	Results              []*SwapiPlanetResponse `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SwapiResponse) Reset()         { *m = SwapiResponse{} }
func (m *SwapiResponse) String() string { return proto.CompactTextString(m) }
func (*SwapiResponse) ProtoMessage()    {}
func (*SwapiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b66d6fe5f50414ae, []int{0}
}

func (m *SwapiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwapiResponse.Unmarshal(m, b)
}
func (m *SwapiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwapiResponse.Marshal(b, m, deterministic)
}
func (m *SwapiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwapiResponse.Merge(m, src)
}
func (m *SwapiResponse) XXX_Size() int {
	return xxx_messageInfo_SwapiResponse.Size(m)
}
func (m *SwapiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SwapiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SwapiResponse proto.InternalMessageInfo

func (m *SwapiResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *SwapiResponse) GetNext() string {
	if m != nil {
		return m.Next
	}
	return ""
}

func (m *SwapiResponse) GetPrevious() string {
	if m != nil {
		return m.Previous
	}
	return ""
}

func (m *SwapiResponse) GetResults() []*SwapiPlanetResponse {
	if m != nil {
		return m.Results
	}
	return nil
}

type SwapiPlanetResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RotationPeriod       string   `protobuf:"bytes,2,opt,name=rotation_period,json=rotationPeriod,proto3" json:"rotation_period,omitempty"`
	OrbitalPeriod        string   `protobuf:"bytes,3,opt,name=orbital_period,json=orbitalPeriod,proto3" json:"orbital_period,omitempty"`
	Diameter             string   `protobuf:"bytes,4,opt,name=diameter,proto3" json:"diameter,omitempty"`
	Climate              string   `protobuf:"bytes,5,opt,name=climate,proto3" json:"climate,omitempty"`
	Gravity              string   `protobuf:"bytes,6,opt,name=gravity,proto3" json:"gravity,omitempty"`
	Terrain              string   `protobuf:"bytes,7,opt,name=terrain,proto3" json:"terrain,omitempty"`
	SurfaceWater         string   `protobuf:"bytes,8,opt,name=surface_water,json=surfaceWater,proto3" json:"surface_water,omitempty"`
	Population           string   `protobuf:"bytes,9,opt,name=population,proto3" json:"population,omitempty"`
	Residents            []string `protobuf:"bytes,10,rep,name=residents,proto3" json:"residents,omitempty"`
	Films                []string `protobuf:"bytes,11,rep,name=films,proto3" json:"films,omitempty"`
	Created              string   `protobuf:"bytes,12,opt,name=created,proto3" json:"created,omitempty"`
	Edited               string   `protobuf:"bytes,13,opt,name=edited,proto3" json:"edited,omitempty"`
	Url                  string   `protobuf:"bytes,14,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwapiPlanetResponse) Reset()         { *m = SwapiPlanetResponse{} }
func (m *SwapiPlanetResponse) String() string { return proto.CompactTextString(m) }
func (*SwapiPlanetResponse) ProtoMessage()    {}
func (*SwapiPlanetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b66d6fe5f50414ae, []int{1}
}

func (m *SwapiPlanetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwapiPlanetResponse.Unmarshal(m, b)
}
func (m *SwapiPlanetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwapiPlanetResponse.Marshal(b, m, deterministic)
}
func (m *SwapiPlanetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwapiPlanetResponse.Merge(m, src)
}
func (m *SwapiPlanetResponse) XXX_Size() int {
	return xxx_messageInfo_SwapiPlanetResponse.Size(m)
}
func (m *SwapiPlanetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SwapiPlanetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SwapiPlanetResponse proto.InternalMessageInfo

func (m *SwapiPlanetResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SwapiPlanetResponse) GetRotationPeriod() string {
	if m != nil {
		return m.RotationPeriod
	}
	return ""
}

func (m *SwapiPlanetResponse) GetOrbitalPeriod() string {
	if m != nil {
		return m.OrbitalPeriod
	}
	return ""
}

func (m *SwapiPlanetResponse) GetDiameter() string {
	if m != nil {
		return m.Diameter
	}
	return ""
}

func (m *SwapiPlanetResponse) GetClimate() string {
	if m != nil {
		return m.Climate
	}
	return ""
}

func (m *SwapiPlanetResponse) GetGravity() string {
	if m != nil {
		return m.Gravity
	}
	return ""
}

func (m *SwapiPlanetResponse) GetTerrain() string {
	if m != nil {
		return m.Terrain
	}
	return ""
}

func (m *SwapiPlanetResponse) GetSurfaceWater() string {
	if m != nil {
		return m.SurfaceWater
	}
	return ""
}

func (m *SwapiPlanetResponse) GetPopulation() string {
	if m != nil {
		return m.Population
	}
	return ""
}

func (m *SwapiPlanetResponse) GetResidents() []string {
	if m != nil {
		return m.Residents
	}
	return nil
}

func (m *SwapiPlanetResponse) GetFilms() []string {
	if m != nil {
		return m.Films
	}
	return nil
}

func (m *SwapiPlanetResponse) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *SwapiPlanetResponse) GetEdited() string {
	if m != nil {
		return m.Edited
	}
	return ""
}

func (m *SwapiPlanetResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*SwapiResponse)(nil), "swapi.SwapiResponse")
	proto.RegisterType((*SwapiPlanetResponse)(nil), "swapi.SwapiPlanetResponse")
}

func init() { proto.RegisterFile("swapi-response.proto", fileDescriptor_b66d6fe5f50414ae) }

var fileDescriptor_b66d6fe5f50414ae = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x6a, 0xdb, 0x40,
	0x10, 0x86, 0x51, 0x65, 0xd9, 0xd6, 0xd8, 0x72, 0xcb, 0xd6, 0x94, 0xc5, 0x94, 0x22, 0x5c, 0x4a,
	0x75, 0xa9, 0x0f, 0x4d, 0x1e, 0xc4, 0x28, 0x87, 0x1c, 0xcd, 0xda, 0x1a, 0x87, 0x05, 0x49, 0x2b,
	0x66, 0x57, 0x76, 0xf2, 0x0c, 0x79, 0x89, 0x3c, 0x6a, 0xd8, 0xd1, 0x2a, 0xc9, 0x21, 0xb7, 0xfd,
	0xbf, 0x6f, 0xe0, 0x9f, 0x41, 0x82, 0xb5, 0xbd, 0xaa, 0x4e, 0xff, 0x23, 0xb4, 0x9d, 0x69, 0x2d,
	0xee, 0x3a, 0x32, 0xce, 0x88, 0x84, 0xe9, 0xf6, 0x39, 0x82, 0xec, 0xce, 0xbf, 0xca, 0xa0, 0xc5,
	0x1a, 0x92, 0x93, 0xe9, 0x5b, 0x27, 0xa3, 0x3c, 0x2a, 0x92, 0x72, 0x08, 0x42, 0xc0, 0xa4, 0xc5,
	0x47, 0x27, 0xbf, 0xe4, 0x51, 0x91, 0x96, 0xfc, 0x16, 0x1b, 0x98, 0x77, 0x84, 0x17, 0x6d, 0x7a,
	0x2b, 0x63, 0xe6, 0x6f, 0x59, 0xdc, 0xc2, 0x8c, 0xd0, 0xf6, 0xb5, 0xb3, 0x72, 0x92, 0xc7, 0xc5,
	0xe2, 0xff, 0x66, 0xc7, 0x85, 0x3b, 0x2e, 0xdb, 0xd7, 0xaa, 0x45, 0x37, 0x56, 0x96, 0xe3, 0xe8,
	0xf6, 0x25, 0x86, 0xef, 0x9f, 0x0c, 0x70, 0xbb, 0x6a, 0x90, 0x57, 0xf2, 0xed, 0xaa, 0x41, 0xf1,
	0x17, 0xbe, 0x92, 0x71, 0xca, 0x69, 0xd3, 0x1e, 0x3a, 0x24, 0x6d, 0xaa, 0xb0, 0xdc, 0x6a, 0xc4,
	0x7b, 0xa6, 0xe2, 0x0f, 0xac, 0x0c, 0x1d, 0xb5, 0x53, 0xf5, 0x38, 0x37, 0x2c, 0x9b, 0x05, 0x1a,
	0xc6, 0x36, 0x30, 0xaf, 0xb4, 0x6a, 0xd0, 0x21, 0xc9, 0xc9, 0x70, 0xcd, 0x98, 0x85, 0x84, 0xd9,
	0xa9, 0xd6, 0x8d, 0x72, 0x28, 0x13, 0x56, 0x63, 0xf4, 0xe6, 0x81, 0xd4, 0x45, 0xbb, 0x27, 0x39,
	0x1d, 0x4c, 0x88, 0xde, 0x38, 0x24, 0x52, 0xba, 0x95, 0xb3, 0xc1, 0x84, 0x28, 0x7e, 0x43, 0x66,
	0x7b, 0x3a, 0xab, 0x13, 0x1e, 0xae, 0xca, 0xd7, 0xcd, 0xd9, 0x2f, 0x03, 0xbc, 0xf7, 0x4c, 0xfc,
	0x02, 0xe8, 0x4c, 0xd7, 0xd7, 0x7c, 0x89, 0x4c, 0x79, 0xe2, 0x03, 0x11, 0x3f, 0x21, 0x25, 0xb4,
	0xba, 0xc2, 0xd6, 0x59, 0x09, 0x79, 0x5c, 0xa4, 0xe5, 0x3b, 0xf0, 0x1f, 0xf1, 0xac, 0xeb, 0xc6,
	0xca, 0x05, 0x9b, 0x21, 0xf0, 0x19, 0x84, 0xca, 0x61, 0x25, 0x97, 0xe1, 0x8c, 0x21, 0x8a, 0x1f,
	0x30, 0xc5, 0x4a, 0x7b, 0x91, 0xb1, 0x08, 0x49, 0x7c, 0x83, 0xb8, 0xa7, 0x5a, 0xae, 0x18, 0xfa,
	0xe7, 0x71, 0xca, 0xbf, 0xcf, 0xcd, 0x6b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0d, 0xa2, 0xe4, 0xb8,
	0x56, 0x02, 0x00, 0x00,
}
